# Generated by Django 5.0.4 on 2024-04-30 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="phone_number",
            new_name="contactNumber",
        ),
    ]
