# Generated by Django 4.2.11 on 2024-04-30 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("seeds", "Seeds"),
                            ("fertilizers", "Fertilizers"),
                            ("feed", "Feed"),
                            ("tools", "Tools"),
                            ("machinery", "Machinery"),
                            ("vehicles", "Vehicles"),
                        ],
                        max_length=50,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("operational", "Operational"),
                            ("needs_repair", "Needs Repair"),
                            ("service_due", "Service Due"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_service_date", models.DateField(blank=True, null=True)),
                ("service_details", models.TextField(blank=True)),
                ("next_service_date", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
