# Generated by Django 5.0.4 on 2024-04-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm_management", "0002_remove_task_description_task_image_subtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="severity",
            field=models.CharField(
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                default="low",
                max_length=6,
            ),
        ),
    ]
