# Generated by Django 5.0.4 on 2024-04-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm_management", "0003_task_severity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "inProgress"),
                    ("on_hold", "onHold"),
                    ("completed", "Completed"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
