# Generated by Django 5.0.4 on 2024-04-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farm_management", "0004_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("inProgress", "In Progress"),
                    ("onHold", "On Hold"),
                    ("completed", "Completed"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
